#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Title: Assignment 2 (Python Practice + Programs)
# Kernel: Python 3
# Python: 3.14.5
# Cells: 5 code, 5 markdown

# ────────────────────────────────────────────────────────────────────────
# # Assignment 2 (Python Practice + Programs)

# ────────────────────────────────────────────────────────────────────────
# ## 1) Practice: Dictionary, Tuple, Set

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

# ---------------- Dictionary Practice ----------------
# Create a dictionary and access values
student = {
    'name': 'Shail',
    'age': 20,
    'course': 'Python'
}

print('Student Dictionary:', student)
print('Name:', student['name'])

# Add/update an item
student['age'] = 21
student['grade'] = 'A'
print('Updated Dictionary:', student)

# ────────────────────────────────────────────────────────────────────────
# %%  [2]

# ---------------- Tuple Practice ----------------
# Tuple is ordered and immutable
colors = ('red', 'green', 'blue')
print('Colors Tuple:', colors)
print('First color:', colors[0])

# Attempting to change tuple element will raise an error
# colors[0] = 'yellow'  # Uncomment to see error

# ────────────────────────────────────────────────────────────────────────
# %%  [3]

# ---------------- Set Practice ----------------
# Set stores unique elements
unique_numbers = {1, 2, 2, 3, 3, 4}
print('Set (unique elements):', unique_numbers)

# Add and remove elements
unique_numbers.add(10)
print('After add(10):', unique_numbers)

unique_numbers.discard(2)
print('After discard(2):', unique_numbers)

# ────────────────────────────────────────────────────────────────────────
# ## 2) Basic Math Operations (using a function)

# ────────────────────────────────────────────────────────────────────────
# %%  [6]

def basic_math_operations(a, b):
    """Return basic math results for two numbers.

    Operations: add, subtract, multiply, divide
    """
    results = {}
    results['add'] = a + b
    results['subtract'] = a - b
    results['multiply'] = a * b

    if b == 0:
        results['divide'] = 'Division by zero is not allowed'
    else:
        results['divide'] = a / b

    return results

# Take 2 number inputs from the user
a = float(input('Enter first number (a): '))
b = float(input('Enter second number (b): '))

outputs = basic_math_operations(a, b)
print("Results:")
for op, val in outputs.items():
    print(f'{op}: {val}')

# ────────────────────────────────────────────────────────────────────────
# ## 3) Check Palindrome Number

# ────────────────────────────────────────────────────────────────────────
# %%  [10]

def is_palindrome_number(n):
    """Check whether a number is a palindrome.

    Steps:
    1) Find reverse of the given number
    2) Compare that number with the reverse number
    3) If equal => Palindrome else not
    """
    n_int = int(n)

    # Palindrome numbers are usually non-negative; handle negative safely
    if n_int < 0:
        return False

    original = n_int
    reverse = 0

    while original > 0:
        digit = original % 10
        reverse = reverse * 10 + digit
        original //= 10

    return n_int == reverse

num = int(input('Enter a number to check palindrome: '))

if is_palindrome_number(num):
    print(num, 'is a Palindrome Number')
else:
    print(num, 'is NOT a Palindrome Number')
