#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Title: Assignment 1 (Student Result + String Methods + Operators + Grading)
# Kernel: Python 3
# Python: 3.x
# Cells: 4 code, 5 markdown

# ────────────────────────────────────────────────────────────────────────
# # Assignment 1 (Student Result + String Methods + Operators + Grading)

# ────────────────────────────────────────────────────────────────────────
# ## 1) Student Total & Percentage

# ────────────────────────────────────────────────────────────────────────
# %%  [3]

# Take student name, class, and 5 subject marks
name = input('Enter student name: ')
class_name = input('Enter class: ')

marks = []
for i in range(1, 6):
    m = float(input(f'Enter marks for subject {i}: '))
    marks.append(m)

total = sum(marks)
percentage = (total / (5 * 100)) * 100

print('\n--- Student Result ---')
print('Name:', name)
print('Class:', class_name)
print('Total Marks:', total)
print('Percentage:', percentage)

# ────────────────────────────────────────────────────────────────────────
# ## 2) String Concatenation + Common String Methods

# ────────────────────────────────────────────────────────────────────────
# %%  [5]

s1 = input('Enter first string: ')
s2 = input('Enter second string: ')

combined = s1 + s2
print('Concatenated string:', combined)

# Generally used string methods
print('lower():', combined.lower())
print('upper():', combined.upper())
print('title():', combined.title())
print('swapcase():', combined.swapcase())
print('capitalize():', combined.capitalize())
print('casefold():', combined.casefold())
print('center(20):', combined.center(20))
print('count("a"):', combined.count('a'))
print('endswith("a"):', combined.endswith('a'))
print('find("a"):', combined.find('a'))
print('isalnum():', combined.isalnum())
print('isdigit():', combined.isdigit())
print('isnumeric():', combined.isnumeric())
print('isspace():', combined.isspace())
print('replace("a", "@"):', combined.replace('a', '@'))

# ────────────────────────────────────────────────────────────────────────
# ## 4) Practice of Assignment Operators

# ────────────────────────────────────────────────────────────────────────
# %%  [7]

x = 10
print('Initial x =', x)

x += 5
print('After x += 5 ->', x)

x -= 3
print('After x -= 3 ->', x)

x *= 2
print('After x *= 2 ->', x)

x /= 4
print('After x /= 4 ->', x)

x //= 2
print('After x //= 2 ->', x)

x %= 3
print('After x %= 3 ->', x)

x **= 2
print('After x **= 2 ->', x)

# ────────────────────────────────────────────────────────────────────────
# ## 5) Grade using Conditional Statement

# ────────────────────────────────────────────────────────────────────────
# %%  [9]

name = input('Enter student name: ')
class_name = input('Enter class: ')

marks = []
for i in range(1, 6):
    m = float(input(f'Enter marks for subject {i}: '))
    marks.append(m)

total = sum(marks)
percentage = (total / (5 * 100)) * 100

if percentage >= 60:
    grade = 'A'
elif percentage >= 50:
    grade = 'B'
elif percentage >= 40:
    grade = 'C'
elif percentage >= 33:
    grade = 'D'
else:
    grade = 'Fail'

print('\n--- Student Result with Grade ---')
print('Name:', name)
print('Class:', class_name)
print('Total Marks:', total)
print('Percentage:', percentage)
print('Grade:', grade)
