# Use the official python:3.12-slim image as the base image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY main.py .

# Run the Python script when the container starts
CMD ["python", "main.py"]
